# NOTE: This is a template. Actual secrets will be created by GitHub Actions
# DO NOT commit real secrets to Git
apiVersion: v1
kind: Secret
metadata:
  name: foodfast-secrets
  namespace: foodfast
type: Opaque
data:
  # Base64 encoded values (will be replaced by CI/CD)
  MONGO_URI: ""
  JWT_SECRET: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
